@startuml
node "Client Device" <<device>> {
  node "Mobile OS" <<executionEnvironment>> {
    artifact "React Native App" <<artifact>>
  }
}

node "Application Server" <<device>> {
  node "Node.js" <<executionEnvironment>> {
    artifact "Core API" <<artifact>>
    artifact "Background Jobs" <<artifact>>
  }
}

node "Database Server" <<device>> {
  node "Firebase " <<database system>> {
    artifact "Users" <<schema>>
    artifact "Expenses" <<schema>>
  }
}

node "Queue Server" <<device>> {
  node " Firebase " <<executionEnvironment>> {
    artifact "CRON Job" <<artifact>>
  }
}

node "Auth Provider" <<device>> {
  node "Firebase" <<executionEnvironment>> {
    artifact "Email/Password" <<artifact>>
  }
}

"Client Device" -- "Application Server" : <<protocol>>\nHTTPS
"Client Device" -- "Auth Provider" : <<protocol>>\nHTTPS
"Application Server" -- "Database Server" : <<protocol>>\nTCP/IP
"Application Server" -- "Queue Server" : <<protocol>>\nTCP/IP
@enduml