name: Build APK on Push

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🏗 Checkout repository
        uses: actions/checkout@v4

      - name: 🏗 Setup Node
        uses: actions/checkout@v4
        with:
          node-version: 18

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.TOKEN_EXPO_ANDROID }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Build APK
        run: eas build --platform android --profile preview --non-interactive --local --output=./app-release.apk

      - name: 📦 Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./app-release.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
